### ISSUE TITLE
Error 500: Please check the filetype and try again

### ISSUE THREAD

**Issue by ronpshah** [TEIC/oxgarage#1]
1) Installed Ubuntu 16.0.4, 64 bit on server.
2) Installed Java 8, Tomcat 8, Openoffice4.1 as part of the requirement.
3) Followed all the instructions on Github

Error 500 is generated while accessing ege-webservice/Conversions and ege-webservice/Validation(inspected on browser
screenshot from 2016-09-22 12-54-49
)

![image](https://cloud.githubusercontent.com/assets/14153912/18919770/58d227aa-856d-11e6-8868-f4b746822c26.png)

Log trace: SEVERE [http-nio-8080-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [ConversionServlet] in context with path [/ege-webservice] threw exception 
java.lang.IllegalArgumentException: unknown plug-in ID pl.psnc.dl.ege.root provided for extension point Converter 
at org.java.plugin.registry.xml.PluginRegistryImpl.getExtensionPoint(PluginRegistryImpl.java:670) 
at pl.psnc.dl.ege.configuration.EGEConfigurationManager.getAvailableConverters(EGEConfigurationManager.java:248) 
at pl.psnc.dl.ege.EGEImpl.initialize(EGEImpl.java:120) 
at pl.psnc.dl.ege.EGEImpl.(EGEImpl.java:109) 
at pl.psnc.dl.ege.webapp.servlet.ConversionServlet.doGet(ConversionServlet.java:129) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) 

If any one can help it would be great. 

Thanks

**Comment by dpancic** [comment]
I solved the same problem by installing saxon and tei-p5-source Debian packages from: http://tei.it.ox.ac.uk/teideb/

**Comment by ronpshah** [comment]
Hello Dalibor,
I installed both that package saxan and tei-p5-source. But now issue is it ask to install openjdk-6-jre but I already have openjdk-8-jre installed so does it create any problem as well as you have any clue does it works with tomcat 8 or only with tomcat 7? 

Any suggestion from you will be of great help to us.

Thanks,
Ronak

**Comment by jamescummings** [comment]
On the main tei-c server it is running an old tomcat 6 install (from memory). I mention it in case that is the problem. The unknown plugin id error makes me think it is not reading the transformation plugin configuration properly.

But not sure.

**Comment by ronpshah** [comment]
Thanks Dalibor & James for valuable input its working with Tomcat 7 now. The issue is resolved by installing some mandatory packages and giving necessary permission to tomcat user (chown -R).
