### ISSUE TITLE
transformation from TEIP5 to PDF goes via plain text

### ISSUE THREAD

**Issue by peterstadler** [TEIC/oxgarage#10]
resulting in, ahem, strange PDFs, i.e. there is almost no text structure and everything in a monospaced font. 

# How to reproduce

take a P5 document, go to http://www.tei-c.org/oxgarage/, select "Documents --> TEI P5 XML Document" as input and "PDF" as output. If you click "Show advanced options?" you'll already see the selected conversion path in the URL, here `http://www.tei-c.org/ege-webservice//Conversions/TEI%3Atext%3Axml/txt%3Atext%3Aplain/pdf%3Aapplication%3Apdf/` which shows `txt%3Atext%3Aplain` as an intermediate step.

# Ideas

@jamescummings  wrote:

> If I'm right the TEI to Latex config bit is at:

> https://github.com/TEIC/oxgarage/blob/master/tei-converter/src/main/java/pl/psnc/dl/ege/tei/TEIConverter.java#L349-L359

> But the auto-determined pipeline is done elsewhere when it tries to find the shortest path. Why it seems to think that should be via plain text eludes me when we clearly have a direct version of that.

> Hard coded direct transformations are usually in https://github.com/TEIC/oxgarage/blob/master/ege-xsl-converter/src/main/resources/META-INF/plugin.xml but TEI to Latex or PDF isn't there so must be handled separately.

**Comment by peterstadler** [comment]
I was just testing this on my local machine and changed the weight for TEI2TXT from 5 to 15 (see https://github.com/TEIC/oxgarage/blob/c58ab7743e2d4f45b7c03e3306759d4e15f8cd34/tei-converter/src/main/java/pl/psnc/dl/ege/tei/Format.java#L24). This resulted in the path `TEI P5 XML Document -> OpenOffice Text  ->  PDF` which produced a better output. 

But really confuses me that there seems to be no conversions defined at all from `LaTeX  -> PDF` nor `FO  ->  PDF`. Thus, the detour via OpenOffice Text!

I could imagine that leaving out those conversions might have been on purpose(?) because it adds more dependencies etc. to the overall service? But TEI users definitely expect these outputs!

**Comment by jamescummings** [comment]
It does seem strange, doesn't it? What happens if you try to manually add TXT to TEI to LaTeX to PDF with a higher weighting?

**Comment by peterstadler** [comment]
I fear, there is no LaTeX to PDF conversion predefined, at all! At least, I can't find one …
Another evidence for this claim: There is no dependency on LaTeX mentioned in the build instructions for OxGarage!

**Comment by jamescummings** [comment]
Ah I see. I'm guessing that Sebastian did this to minimise the conversion dependencies, but it does seem a shame. Going via OpenOffice I guess is ok, but I have a feeling that (not for TXT but other conversions) going first to DOCX then using that to get to PDF from OpenOffice would be better than the direct conversion to ODT.  I think that conversion stagnated a bit after the DOCX one was so well developed.

**Comment by peterstadler** [comment]
I took another look at this issue and it seems to me that the simple fix (changing the weight for TEI2TXT from 5 to 15) will be the low-hanging-fruit we should aim at (and immediately improve the PDF output).

Everything else is harder:

*  `TEI -> DOCX -> PDF` would probably be better since the TEI -> DOCX transformation is better than ODT -> DOCX. But: Currently, OxGarage has no direct transformation from DOCX -> PDF but will convert From DOCX to PDF via TEI->ODT->PDF (with the above fix in place; otherwise it will substitute ODT with plain text)
* `TEI -> LaTeX -> PDF` will be even better, but there is currently no LaTeX support in OxGarage (as an input format)

Both issues deserve their own tickets – if anyone volunteers to implement this?

**Comment by lb42** [comment]
Tei latex pdf is something teipiblisher now does better I believe. Maybe Something could be taken from that work?

reluctantly using Outlook for Android<https://aka.ms/ghei36>

________________________________
