### ISSUE TITLE
Support XSLT3

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/oxgarage#13]
At least one of the TEI Stylesheets will soon be updated to use XSLT3 (odd2json.xsl). Oxgarage won't be able to use it unless the code is updated to use XSLT3.

Several changes will be needed to do this. This is what I managed to figure out (see the branch [RV-xslt3attempt](https://github.com/TEIC/oxgarage/tree/RV-xslt3attempt)):

## Update Saxon 9 to > 9.8
This could be done in the [TEIConverter pom.xml](https://github.com/TEIC/oxgarage/blob/master/tei-converter/pom.xml) file:
```xml
<dependency>
  <groupId>net.sf.saxon</groupId>
  <artifactId>Saxon-HE</artifactId>
  <version>9.8</version>
</dependency>
```
But this version doesn't seem to be available on Maven, so it will need to be installed manually (similarly to other dependencies). So we'll have to update the saxon jar and add this line to the readme:
```
mvn install:install-file -DgroupId=net.sf.saxon -DartifactId=commons-cli -Dversion=9.8 -Dpackaging=jar -Dfile=jsaxon9he.jar
```
## Update TEIConverter to use XSLT 3
Saxon's API introduces dedicated methods to run XSLT3 transformations. This *should* be able to run XSLT 2 and 1 transformations as well, but the behavior is different. [See the documentation](https://www.saxonica.com/documentation/#!using-xsl/embedding/s9api-transformation). For example "Unlike XsltTransformer, an Xslt30Transformer is not a Destination. To pipe the results of one transformation into another, the target should be an XsltTransfomer rather than an Xslt30Transformer."

I tried switching to this API, and got Maven to compile, but the transformation still won't work. I'm sure there's more that needs to be done, but I don't really know how to continue! 

## Complete and test implementation
Can someone who's better versed in Java take it from here, or otherwise implement this feature independently?

**Comment by hcayless** [comment]
This should be done as of 7587d44.
