### ISSUE TITLE
Error: class pl.psnc.dl.ege.exception.ConverterException (Can't convert any file to any other file format)

### ISSUE THREAD

**Issue by ronpshah** [TEIC/oxgarage#2]
Hello,

We successfully installed OxGarage on our local server but while converting any file format to some other format we are getting following error:

Error: class pl.psnc.dl.ege.exception.ConverterException 
null

![image](https://cloud.githubusercontent.com/assets/14153912/20110077/e5491c44-a5b0-11e6-943b-6b1a15fb4dce.png)

I feel the issue is similar to Jure facing in past https://github.com/sebastianrahtz/oxgarage/issues/6

Thanks,
Ronak

**Comment by peterstadler** [comment]
I just created a [Docker image for OxGarage](https://github.com/peterstadler/oxgarage-docker) – maybe this could help? 

Concerning your question, have you installed OpenOffice or LibreOffice and adjusted the office.home variable?

**Comment by peterstadler** [comment]
The Docker image mentioned in the comment above is deprecated now. Please pull from https://hub.docker.com/r/teic/oxgarage/

Closing the issue because it seems outdated—but please do not hesitate to reopen if the problem still persists.
