### ISSUE TITLE
Error 500 upon accessing http://www.tei-c.org/oxgarage/

### ISSUE THREAD

**Issue by RJP43** [TEIC/oxgarage#23]
Hello and happy Sunday, 

I am getting the following error when visiting the [OxGarage](http://www.tei-c.org/oxgarage/_) site: 
  
![oxgarageerror](https://user-images.githubusercontent.com/8645521/42736408-0de3c028-882c-11e8-9db3-6aa2c5562fd1.JPG)

Please advise to whether this is temporary or not. Thank you!

**Comment by ebeshero** [comment]
Hi @RJP43 ! There was a disk failure recently that affected many sites using the ADHO hosting service, so lots of TEI services aren't working properly right now.  People are working on it, so I don't think this is permanent...

**Comment by peterstadler** [comment]
Meanwhile you can use a second OxGarage instance at https://oxgarage-paderborn.tei-c.org

**Comment by RJP43** [comment]
@peterstadler and @ebeshero Thank you both!

**Comment by RJP43** [comment]
@peterstadler, unfortunately, the second instance is giving me an error to check the file type even though I have correctly selected the source file type. Any idea when the service will be available again?

**Comment by jamescummings** [comment]
@RJP43 Can you produce a minimal file that causes the same error and share it with us?  Also try on http://oxgarage.tei-c.org/ which we've just setup while repairing the main TEI site. What type of file is it?

**Comment by RJP43** [comment]
@jamescummings nevermind it must have just got hung up ran it several more times and it just now went through. Thanks for your speedy response.

**Comment by peterstadler** [comment]
ok, glad it works now – closing this issue.
Feel free to reopen if the issue strikes back …

**Comment by liladude** [comment]
Hello, I'm not sure my problem belongs to this thread, but I see the very same error. I just created my OxGarage server on Debian with Tomcat 9 with unconventional port , and I have this error on the webclient side, and a list of "Java.lang.ExceptionInInitializerError at XXX" on the server side. I was wondering if I missed some steps with configuration.
