### ISSUE TITLE
ODD -> ODDC -> JSON ignores image parameters

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/oxgarage#29]
When converting a compiled ODD (ODDC) to JSON, setting the following parameters will *correctly* result in ignoring links to images in the ODD:

```xml
<property id="oxgarage.getImages">false</property>
<property id="oxgarage.getOnlineImages">false</property>
<property id="oxgarage.textOnly">true</property>
```

However, when calling the endpoint that performs ODD -> ODDC -> JSON in one go, the parameters seems to be ignored, resulting in an error. Example endpoint (formatted for clarity):

```
ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/oddjson%3Aapplication%3Ajson/conversion?
    properties=
    <conversions><conversion index="0">
        <property id="oxgarage.getImages">false</property>
        <property id="oxgarage.getOnlineImages">false</property>
        <property id="oxgarage.lang">en</property>
        <property id="oxgarage.textOnly">true</property>
        <property id="pl.psnc.dl.ege.tei.profileNames">default</property>
    </conversion></conversions>
```

If the parameters should be passed differently, please advise. Otherwise there might be a bug in passing parameters to *all* steps in the ODD -> ODDC -> JSON chain.

Example ODD with images that is failing: http://www.tei-c.org/Vault/P5/3.4.0/xml/tei/custom/odd/tei_jtei.odd

**Comment by raffazizzi** [comment]
Bump :) @peterstadler @hcayless

**Comment by hcayless** [comment]
Looking at the code, it *seems* like it ought to work properly. I wonder if the issue is in the input. I notice that `<conversion>` has an `@index` property. What if you add a second one with `@index="1"` and the relevant properties? E.g.

```xml
ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/oddjson%3Aapplication%3Ajson/conversion?
    properties=
    <conversions><conversion index="0">
        <property id="oxgarage.getImages">false</property>
        <property id="oxgarage.getOnlineImages">false</property>
        <property id="oxgarage.lang">en</property>
        <property id="oxgarage.textOnly">true</property>
        <property id="pl.psnc.dl.ege.tei.profileNames">default</property>
    </conversion>
    <conversion index="1">
        <property id="oxgarage.getImages">false</property>
        <property id="oxgarage.getOnlineImages">false</property>
        <property id="oxgarage.lang">en</property>
        <property id="oxgarage.textOnly">true</property>
        <property id="pl.psnc.dl.ege.tei.profileNames">default</property>
    </conversion>
</conversions>
```
I can try testing this later, but have to move on to the next fire right now :-)

**Comment by raffazizzi** [comment]
Yes it works!! Thank you for looking into this :+1:
