### ISSUE TITLE
CORS issue with docker-compose setup

### ISSUE THREAD

**Issue by jthomae1** [TEIC/oxgarage#34]
We always run into a CORS error with our docker setup. At first I will describe the setup to avoid obscurities.

docker-compose:

    oxgarage:
        image: teic/oxgarage:latest
        container_name: oxgarage
        restart: unless-stopped
        environment:
          - WEBSERVICE_URL=http://localhost:8081/ege-webservice/
        volumes:
          - /opt/stylesheets/tei-xsl-7.47.0/doc/tei-xsl:/usr/share/xml/tei/stylesheet
          - /opt/stylesheets/tei-3.5.0/xml/tei/odd:/usr/share/xml/tei/odd
        ports:
          - 8081:8081

We are using an apache webserver as a proxy in front of oxgarage:

Part of the default-ssl.conf:

    ProxyPass /oxgarage/ http://localhost:8081/
    ProxyPassReverse /oxgarage/ http://localhost:8081/

The url to oxgarage is something like **https://<example.de>/oxgarage**, which is working with the apache ProxyPass. Here the result with the CORS error:
![Bildschirmfoto 2019-05-02 um 15 08 00](https://user-images.githubusercontent.com/8523176/57077481-74d97200-6cec-11e9-8af8-12c483aa6fad.png)

What we tried:

1. Adding CORS Header to the apache VirtualHost config in the default-ssl.conf, without result.
2. Adding CORS filter and filter-mapping to the tomcat web.xml inside of the docker container, without result.
3. Changing the WEBSERVICE_URL in the docker-setup to **https://<example.de>/ege-webservice**, which has the effect, that the docker container doesn't start correctly. The tomcat hangs during the start process and nothing happens.

Unfortunately I'm running out of ideas to fix that issue by myself.
Perhaps someone ran into a similar error und could share information or in the best case could provide a solution for it.

Thank you in advance.

**Comment by peterstadler** [comment]
Thanks for the detailed report, I see that you're using the image `teic/oxgarage:latest`. Could you please try with `teic/oxgarage:dev` because CORS support was only added in 81064cb (I believe) *after* the last release.
(the dev version also powers https://oxgarage2.tei-c.org and I consider it stable ;) Nevertheless, we should release an update soon!)

**Comment by jthomae1** [comment]
Hey, thank you for the quick answer!
I tried the `teic/oxgarage:dev` image and the CORS error disappeared.

But the conversion of documents wasn't possible due to another error regarding the webservice I think. The "startpage" is loading properly, but once I select e.g. a document the error appears.

I took another screenshot, maybe it helps to find the reason.

![Bildschirmfoto 2019-05-03 um 19 10 20](https://user-images.githubusercontent.com/8523176/57154043-299c8d80-6dd8-11e9-919c-92ee4999aec0.png)

**Comment by peterstadler** [comment]
It seems the web client (the frontend) can't talk to the web service (the backend)?
NB, The `WEBSERVICE_URL` param should be set to the *external* URL, so in your case that's probably `http://localhost/oxgarage/ege-webservice/` since you access Oxgarage through a reverse proxy.

**Comment by jthomae1** [comment]
That was my intention, too. I will try the external URL, but it seems that the apache ProxyPass config does not work properly for `http://localhost:8081/ege-webservice/`. I'll try to fix that first.

**Comment by jthomae1** [comment]
I changed the webservice url and it works now.
The actual config for the `WEBSERVICE_URL` is `https://ourdomain.de/ege-webservice/`.

The webservice is not reachable if there is a subpath between the host and /ege-webservice/.  

I tried it locally with a subpath, and the converter works, but the webservice wasn't available at localhost:8080/example/ege-webservice. A tomcat status 404 was shown in the browser instead of the "Restful" Message. Maybe that information will help.

Sad to say, but I ran in another error while converting from or to docx or xlsx documents.

The beginning of the of the stack trace:

```
12:11:54,341         INFO TEIConverter:149 - 2019/05/09 12:11:54: Converting FROM:  Documents:Microsoft Word (.docx):docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document TO Documents:TEI P5 XML Document:TEI,text/xml WITH profile default
12:11:54,345         INFO TEIConverter:149 - 2019/05/09 12:11:54: Converting FROM:  Documents:TEI P5 XML Document:TEI,text/xml TO Documents:Plain text:txt,text/plain WITH profile null
Error 
  I/O error reported by XML parser processing
  file:/usr/share/xml/tei/stylesheet/profiles/default/docx/from.xsl:
  /usr/share/xml/tei/stylesheet/profiles/default/docx/from.xsl (No such file or directory)
12:11:54,402        ERROR TEIConverter:173 - I/O error reported by XML parser processing file:/usr/share/xml/tei/stylesheet/profiles/default/docx/from.xsl: /usr/share/xml/tei/stylesheet/profiles/default/docx/from.xsl (No such file or directory)
net.sf.saxon.s9api.SaxonApiException: I/O error reported by XML parser processing file:/usr/share/xml/tei/stylesheet/profiles/default/docx/from.xsl: /usr/share/xml/tei/stylesheet/profiles/default/docx/from.xsl (No such file or directory)
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:742)
	at pl.psnc.dl.ege.tei.ComplexConverter.getTEI(ComplexConverter.java:249)
	at pl.psnc.dl.ege.tei.ComplexConverter.toTEI(ComplexConverter.java:204)
	at pl.psnc.dl.ege.tei.TEIConverter.transformFromDocX(TEIConverter.java:790)
	at pl.psnc.dl.ege.tei.TEIConverter.convertDocument(TEIConverter.java:200)
	at pl.psnc.dl.ege.tei.TEIConverter.convert(TEIConverter.java:154)
	at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
	at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:45)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by peterstadler** [comment]
Great that CORS now works for you!

The current error message "/usr/share/xml/tei/stylesheet/profiles/default/docx/from.xsl (No such file or directory)" seems to indicate a wrong path for the Stylesheets.
Given the information from your docker-compose file I suspect the first volume: Could you try and replace with the following?
```
/opt/stylesheets/tei-xsl-7.47.0/xml/tei/stylesheet:/usr/share/xml/tei/stylesheet
``` 
(Given the directory structure of the released archive this will point at the proper stylesheets location not at their documentation.)

**Comment by jthomae1** [comment]
Thank you very much, I was a little bit confused because all other file types worked. Didn't expect the docker volume therefore.
But the stylesheet url was the problem, now everything seems to be fine.

**Comment by peterstadler** [comment]
Great to hear that everything(?) seems to work now :)

Let's close that issue here -- but feel free to open another one for any other problem you encounter!
