### ISSUE TITLE
Oxgarage uses an old OUCS favicon.ico, change to the TEI favicon.ico?

### ISSUE THREAD

**Issue by jamescummings** [TEIC/oxgarage#36]
Oxgarage, however installed, uses a favicon.ico which is an old Oxford University Computing Services favicon.ico ... Given the OUCS doesn't even exist any more (it became IT Services at University of Oxford in 2012), perhaps we should change it to be the TEI-C favicon.ico that we have somewhere.

**Comment by peterstadler** [comment]
Is there an "official" TEI favicon? Is it the two red vertical bars I see at tei-c.org (but don't recognise)?

Otherwise I found something on the old server that looks like the TEI logo in (very) small.

**Comment by ebeshero** [comment]
I suspect we should just use the TEI logo as you're suggesting, @peterstadler , and also ask Luis to implement it on the official website. Those two red bars look weird to me on my browser tab when I have the TEI website open...

**Comment by jamescummings** [comment]
[favicon.ico.zip](https://github.com/TEIC/oxgarage/files/3335898/favicon.ico.zip)

Here is an attached favicon.ico (inside a zip because you know github allowing me to upload a .ico file would be a massive security risk, but a zip is fine....)
