### ISSUE TITLE
Commercial Use

### ISSUE THREAD

**Issue by navraj28** [TEIC/oxgarage#44]
Hello,
     Is there a cost when used Commercially? Is this software used for commercial purposes by other organizations?

**Comment by peterstadler** [comment]
> Is there a cost when used Commercially? 

Disclaimer first: I'm not a lawyer and these legal issues are beyond me. That said, the OxGarage is licensed under [GPL-v3.0](https://github.com/TEIC/oxgarage/blob/dev/LICENSE) which should not stop anybody from using it commercially, I believe.

> Is this software used for commercial purposes by other organizations?

I don't know of any commercial applications using the OxGarage.

**Comment by hcayless** [comment]
As Peter says, there is no barrier to commercial use, *except* that commercial users must share any improvements they make to the source code. https://github.com/TEIC/oxgarage/blob/dev/LICENSE gives a good overview of the terms. Note that OxGarage is derivative of an earlier project, and so we might not be in a position to negotiate exceptions to the terms of the GPL v. 3.0 license.

**Comment by peterstadler** [comment]
Stale issue closed.

Since we're going to archive this repo please feel free to reopen at the successor https://github.com/TEIC/TEIGarage/issues if needed.
