### ISSUE TITLE
No conversion occurs

### ISSUE THREAD

**Issue by nthieberger** [TEIC/oxgarage#46]
I have uploaded an xhtml doc to convert to TEI but nothing happens. I have tried in Chrome, Firefox, and Safari.

**Comment by martindholmes** [comment]
Hi @nthieberger. Are you able to share the document you've been trying to convert?

**Comment by nthieberger** [comment]
Hi @martindholmes , I found an error in the source doc that was clearly fatal to the conversion, sorry ! All ok now.
