### ISSUE TITLE
add deprecation note to the web client

### ISSUE THREAD

**Issue by peterstadler** [TEIC/oxgarage#48]
and redirect users (not automatically but via link) to teigarage.tei-c.org.

If everything works fine we can finally replace the OxGarage deployment with [TEIGarage](https://github.com/TEIC/teigarage) at the domain oxgarage.tei-c.org, so all endpoints remain stable.

This is part of the migration from OxGarage to TEIGarage, see poster from TEI 2022 conference https://zenodo.org/record/7061525

**Comment by anneferger** [comment]
Adding note [here](https://github.com/TEIC/oxgarage/blob/dev/ege-webclient/src/main/webapp/index.jsp) and push the Docker Image to DockerHub afterwards.

**Comment by anneferger** [comment]
To do:
`docker build . -t teic/oxgarage`
and push to https://hub.docker.com/r/teic/oxgarage (@peterstadler because of access rights), make sure to keep the required odd/stylesheet folders on the server where it needs to be deployed

**Comment by peterstadler** [comment]
image built, tested and pushed. Final steps before archiving the repo …
