### ISSUE TITLE
Enable CORS on <http://www.tei-c.org/ege-webservice/>

### ISSUE THREAD

**Issue by Conal-Tuohy** [TEIC/oxgarage#7]
Might I ask if [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) could be more fully enabled for the [TEI's OxGarage](http://www.tei-c.org/ege-webservice/)?

Currently the service is configured with the following CORS header:

```
Access-Control-Allow-Origin: *
```

This allows any CORS-constrained client (i.e. a browser-based web app) to issue a request to the service, but it still leaves some important restrictions in place. In order for a browser-based app to submit a request with a `Content-Type` header specifying an XML content type (or any content type other than `application/x-www-form-urlencoded`, `multipart/form-data`, or `text/plain`), and to access the value of the `Content-Disposition` header in the server's response, the server should be configured to emit the following CORS headers:

| Header Name                   | Header Value         |
| ----------------------------- | -------------------- |
| Access-Control-Allow-Origin   | *                    |
| Access-Control-Allow-Headers  | Content-Type         |
| Access-Control-Expose-Headers | Content-Disposition  |

**Comment by peterstadler** [comment]
I think the OxGarage at http://www.tei-c.org is running on an Tomcat6 and I'm not trying to touch this at present. That said, the Docker image at https://hub.docker.com/r/teic/oxgarage/ employs a Tomcat7 and reading http://tomcat.apache.org/tomcat-7.0-doc/config/filter.html#CORS_Filter, the default CORS setup should support the above headers. If not, I'm happy to add the respective directives to the image. If you're still interested (after a year), you can try a current OxGarage running with the Tomcat7 image at https://oxgarage.euryanthe.de/ege-webservice.

**Comment by peterstadler** [comment]
Testing the current installation with `curl`
```bash
curl -L -H "Origin: http://example.com/" \                                                                                                                                               
 -H "Access-Control-Request-Method: POST" \
 -H "Access-Control-Request-Headers: X-Requested-With" \
 -X OPTIONS  -v  http://oxgarage.tei-c.org/ege-webservice
```

outputs
```txt 
…
< content-length: 0
< access-control-allow-origin: *
< access-control-expose-headers: Content-Disposition
< vary: Access-Control-Request-Headers,Access-Control-Request-Headers,access-control-request-method
< access-control-max-age: 1800
< access-control-allow-methods: HEAD,POST,GET,OPTIONS
< access-control-allow-headers: origin,x-requested-with,access-control-request-headers,content-type,access-control-request-method,accept
< strict-transport-security: max-age=31536000
```

so I assume it's working. Closing here but feel free to add more requests ;)
